# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Module-specific service configurations
    # shared
    App\Shared\Messenger\Middleware\ValidationMiddleware:
        tags: [ messenger.middleware ]

    App\Shared\Messenger\Middleware\ErrorLoggingMiddleware:
        tags: [ messenger.middleware ]

    App\Shared\Messenger\Middleware\PerformanceMiddleware:
        tags: [ messenger.middleware ]

    # user module
#    App\User\Domain\Contracts\UserRepositoryInterface: '@App\User\Infrastructure\InMemory\InMemoryUserRepository'
    App\User\Domain\Contracts\UserRepositoryInterface: '@App\User\Infrastructure\Doctrine\Repository\DoctrineUserRepository'

    # task module
    App\Task\Infrastructure\Doctrine\Repository\DoctrineTaskRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Task\Domain\Contracts\TaskRepositoryInterface: '@App\Task\Infrastructure\Doctrine\Repository\DoctrineTaskRepository'

    App\Task\Application\Strategy\TodoTaskStatusStrategy:
        tags: [ 'app.task_status_strategy' ]

    App\Task\Application\Strategy\InProgressTaskStatusStrategy:
        tags: [ 'app.task_status_strategy' ]

    App\Task\Application\Strategy\DoneTaskStatusStrategy:
        tags: [ 'app.task_status_strategy' ]

    App\Task\Application\Strategy\TaskStatusStrategyResolver:
        arguments:
            $strategies: !tagged_iterator app.task_status_strategy
