framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
#            async: 'redis://redis:6379/messages'
            async:
                dsn: 'redis://redis:6379/messages'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000

            failed: 'doctrine://default?queue_name=failed'
#            failed: 'redis://redis:6379/failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - App\Messenger\Middleware\ErrorLoggingMiddleware
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            'App\Message\*': async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
